spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
    generate-ddl: false
app:
  auth:
    token:
      secret-key: ${JWT_SECRET_KEY}
      refresh-cookie-key: ${REFRESH_COOKIE_KEY}
  oauth2:
    authorizedRedirectUri: ${GOOGLE_OAUTH2_REDIRECT_URI}
